language: java
jdk: openjdk7
before_install: gem install fpm
install:
- sudo apt-get update
- DEBIAN_FRONTEND=noninteractive sudo apt-get install -y rpm
script: mvn clean install -Prpm -DbuildNumber=$TRAVIS_BUILD_NUMBER
after_success: SWOOKIEE_VERSION=$(mvn org.apache.maven.plugins:maven-help-plugin:2.1.1:evaluate -Dexpression=swookiee.version|grep -Ev '(^\[|Download\w+:)')
deploy:
  provider: releases
  api_key:
    secure: WDFshkkJVYKBDEOGprE69NiKUPUuuwVwZIfrJpPwmaWq91e1i0oOZo5aLg4hzsBl2ombmQ0hGJV2BzdnaC8rK7pLmfGW6be3bHlaDUSf5LU1bQ9p3sfUdN996AL7r7B0iSLGtnvm2CL8IvzQc5dvajPQPDKS+1Lzeqmd1iZkGTY=
  file: target/swookiee-$SWOOKIEE_VERSION-$TRAVIS_BUILD_NUMBER.noarch.rpm
  skip_cleanup: true
  on:
    tags: true
    all_branches: true
