language: java
jdk: openjdk7
branches:
  only:
  - master
before_install: gem install fpm
install:
- sudo apt-get update
- DEBIAN_FRONTEND=noninteractive sudo apt-get install -y rpm
script: mvn clean install -Prpm -DbuildNumber=$TRAVIS_BUILD_NUMBER
deploy:
  provider: releases
  api_key:
    secure: GAbOPglBf0F2WrF7czfZdLSJI3t807M16N0SwmSaeDWD4/LIf56oUrsH1RSIba1RS7p8XESzgmnZePM9csIIeT7LQJSJtCBa7zJbNvhoX7nam+HY/QEO9Nnp4JMkUXs/GQ4DTy9srmW6n48rq+kZBVyX3/yDHkq0giA2T/ghgkE=
  file: target/swookiee-1.0.0_SNAPSHOT-$TRAVIS_BUILD_NUMBER.noarch.rpm
  on:
    repo: swookiee/packages
