language: java
jdk: openjdk7
before_install: gem install fpm
install:
- sudo apt-get update
- DEBIAN_FRONTEND=noninteractive sudo apt-get install -y rpm
script: sh -c "if [ -z '$TRAVIS_TAG' ]; then mvn -X clean install -Prpm; else mvn -X clean install -Prpm -Dtag=$TRAVIS_TAG; fi"
after_success: SWOOKIEE_VERSION=$(mvn org.apache.maven.plugins:maven-help-plugin:2.1.1:evaluate -Dexpression=swookiee.version|grep -Ev '(^\[|Download\w+:)')
deploy:
  provider: releases
  api_key:
    secure: "nkW8c98hEkQzwmfB1bnne7uaiwmj0QpWOTbRdcSlZW+hzimOYw4vqtnsj5xx8JN2iiiazdudh0B7pXSWAgiYIl2mCZvqJo4mUlepgpB8Gqg8Fjn/4oqSmWyJhEbn+ZLH/fyBOtA93x6JQzj4c9ytWv616N+f01OfR7fhZHZWlB2C7ij9bHmllXvzoi1lKIzL5kK9a7PRjx2kSCOoNVEhiik70iI8AJK22/RXs5pixnPngMmFzYfcwPcr9fGXGyNwAnoAR0tAmnAGeh+QuaM6sagCZ0+yiucnQ04FpCI9eem99H/RTA5PEACN1dUZMvAJNnQzGmzUjS0ccz/kOvMsTY3ZYPlAaeuaz/5YlivYOGRuBSmECRSanUdoDfkL1rx6CqE//DGgrNBAZVF/knD7C/LLHfmnQYmjUuwZxeFabgdJipj9W8bu1AZiPQ4G2mfBQHOrOKgFPx9Jg04cKKoVL05inPykGT79f6Pr9U/QSK8yBsSwJArly2vCOPVkZrxCP9u3bEJZwmMu1dIvU92trqz4Tb+2WpJKasRsyFSSuOncU+T5kRPLfmue4qBxFcMEDbBz7KGIV+1X2ldJXbqisBkjrvWOquv2GQoPib5SMdOuoDFuLmRaNjuZmqN4lOs1Jz0Ny67dMciiTzFUVMIgtbSE+6D8V+EI68vNbutaB/4="
  file: target/swookiee-$SWOOKIEE_VERSION-$TRAVIS_TAG.noarch.rpm
  skip_cleanup: true
  on:
    tags: true
    all_branches: true
