language: java
jdk: openjdk7
branches:
  only:
  - master
before_install: gem install fpm
install:
- sudo apt-get update
- DEBIAN_FRONTEND=noninteractive sudo apt-get install -y rpm
script: mvn clean install -Prpm -DbuildNumber=$TRAVIS_BUILD_NUMBER
after_success: ./upload-to-gh-pages.sh
env:
  global:
    secure: kxPyOhp5aMngzF+Dd62rweknG4toCHE0kC3v6bW2NiKVpaY6QpuFi5yrxdYvPT6H4PJTP/ehWcTUsF8JbOwrJe2pHP9c1e4ZN5uKCRCmi/I1BYzs5nTwC9Lu6PNF2aJTTAtiwnAN3xwwdMOLt+erWCN8rbYdFfwKNbRE2SyNwIs=
